/**
 * AI Context Writer Tests
 *
 * Tests for AGENTS.md generation from project data and the writer that lands
 * AGENTS.md plus CLAUDE.md pointer files in the project.
 *
 * Covers EDS projects, headless projects, block libraries, and conditional sections.
 */

import { generateAgentsMd } from '@/features/project-creation/services/aiBundle/aiContextWriter';

import type { InstalledBlockLibrary, CustomBlockLibrary } from '@/types/blockLibraries';
import {
    STACKS,
    makeEdsProject,
    makeEdsStorefrontInstance,
    makeHeadlessProject,
} from './aiContextWriter.testUtils';

// ─── Helpers ────────────────────────────────────────────────────────────────

// ─── Tests ───────────────────────────────────────────────────────────────────

describe('aiContextWriter', () => {
    describe('generateAgentsMd', () => {
        it('marks the file as generated (ADR-013 edits-kept banner) so the freeze trade is stated', () => {
            const result = generateAgentsMd(makeEdsProject(), STACKS);
            expect(result).toMatch(/GENERATED by Adobe Demo Builder/i);
            expect(result).toMatch(/Edits are kept/);
            expect(result).toMatch(/stops receiving bundle updates/);
        });

        describe('EDS projects', () => {
            it('includes the GitHub repo URL', () => {
                const project = makeEdsProject();
                const result = generateAgentsMd(project, STACKS);

                expect(result).toContain('https://github.com/owner/my-repo');
            });

            it('includes the AEM live URL', () => {
                const project = makeEdsProject();
                const result = generateAgentsMd(project, STACKS);

                expect(result).toContain('https://main--my-repo--owner.aem.live');
            });

            it('includes the AEM preview URL', () => {
                const project = makeEdsProject();
                const result = generateAgentsMd(project, STACKS);

                expect(result).toContain('https://main--my-repo--owner.aem.page');
            });

            it('includes the DA.live authoring URL', () => {
                const project = makeEdsProject();
                const result = generateAgentsMd(project, STACKS);

                // # is escaped by escapeMarkdown at the output boundary
                expect(result).toContain('https://da.live/\\#/my-org/my-site');
            });

            it('uses the Experience Workspace canvas URL when the project is set to EW', () => {
                // Per-project authoringExperience wins over the global default (UE),
                // so the resolver returns EW without reading vscode config.
                const project = makeEdsProject({
                    componentInstances: {
                        'eds-storefront': makeEdsStorefrontInstance({
                            authoringExperience: 'experience-workspace',
                        }),
                    },
                });
                const result = generateAgentsMd(project, STACKS);

                // Param-less production canvas form (default ewCanvasBranch '') with
                // the extensionless `index` doc (da.live appends `.html` itself; a
                // `.html` suffix double-appends and 404s). escapeMarkdown escapes only `#`.
                expect(result).toContain('https://da.live/canvas\\#/my-org/my-site/index');
                expect(result).not.toContain('https://da.live/\\#/my-org/my-site');
            });

            it('includes the local storefront path', () => {
                const project = makeEdsProject();
                const result = generateAgentsMd(project, STACKS);

                expect(result).toContain('/projects/test-project/components/eds-storefront');
            });
        });

        describe('PDP routing section', () => {
            it('includes the PDP Routing section for EDS projects', () => {
                const result = generateAgentsMd(makeEdsProject(), STACKS);
                expect(result).toContain('## PDP Routing');
            });

            it('warns against per-product DA pages and folder mapping', () => {
                const result = generateAgentsMd(makeEdsProject(), STACKS);
                expect(result).toContain('do not');
                expect(result).toContain('per-product DA pages');
                expect(result).toContain('folder mapping');
            });

            it('documents the canonical BYOM overlay routing and SC template handoff', () => {
                const result = generateAgentsMd(makeEdsProject(), STACKS);
                expect(result).toContain('/products/default');
                expect(result).toContain('Phase 2 LIVE');
                expect(result).toContain('content.overlay');
            });

            it('provides a debugging checklist for 404s', () => {
                const result = generateAgentsMd(makeEdsProject(), STACKS);
                expect(result).toContain('demoBuilder.byom.overlayUrl');
                expect(result).toContain('render-pdp');
                expect(result).toContain('404.html');
            });

            it('links to the architecture doc', () => {
                const result = generateAgentsMd(makeEdsProject(), STACKS);
                expect(result).toContain('docs/architecture/eds-byom-pdp-routing.md');
            });

            it('omits the PDP Routing section for headless projects', () => {
                const result = generateAgentsMd(makeHeadlessProject(), STACKS);
                expect(result).not.toContain('## PDP Routing');
            });
        });

        describe('headless projects', () => {
            it('includes the Commerce endpoint URL', () => {
                const project = makeHeadlessProject();
                const result = generateAgentsMd(project, STACKS);

                expect(result).toContain('https://commerce.example.com');
            });

            it('does not include DA.live URL', () => {
                const project = makeHeadlessProject();
                const result = generateAgentsMd(project, STACKS);

                expect(result).not.toContain('da.live');
            });

            it('does not include GitHub repo URL', () => {
                const project = makeHeadlessProject();
                const result = generateAgentsMd(project, STACKS);

                expect(result).not.toContain('github.com/owner/my-repo');
            });

            it('does not include AEM URLs', () => {
                const project = makeHeadlessProject();
                const result = generateAgentsMd(project, STACKS);

                expect(result).not.toContain('.aem.live');
                expect(result).not.toContain('.aem.page');
            });
        });

        describe('reporting style (handoff convention)', () => {
            it('includes the Reporting Back to the User section for EDS projects', () => {
                const result = generateAgentsMd(makeEdsProject(), STACKS);

                expect(result).toContain('## Reporting Back to the User');
                expect(result).toContain('Lead with status in one line');
                expect(result).toContain('Never paste raw tool-result JSON');
            });

            it('includes the reporting convention for headless projects too', () => {
                const result = generateAgentsMd(makeHeadlessProject(), STACKS);

                expect(result).toContain('## Reporting Back to the User');
            });
        });

        describe('mesh endpoint', () => {
            it('includes the mesh endpoint URL when present', () => {
                const project = makeHeadlessProject({
                    appBuilderComponents: {
                        mesh: {
                            kind: 'mesh',
                            status: 'deployed',
                            source: { owner: '', repo: '' },
                                endpoint: 'https://graph.adobe.io/api/mesh/abc123',
                                envVars: {},
                                sourceHash: null,
                                lastDeployed: new Date().toISOString(),
                                            },
                    },
                });
                const result = generateAgentsMd(project, STACKS);

                expect(result).toContain('https://graph.adobe.io/api/mesh/abc123');
            });

            it('omits the mesh section when no mesh endpoint', () => {
                const project = makeHeadlessProject();
                const result = generateAgentsMd(project, STACKS);

                expect(result).not.toContain('graph.adobe.io');
            });
        });

        describe('Adobe org-context guidance', () => {
            it('explains per-operation org targeting and that ORG_MISMATCH must not be retried', () => {
                const project = makeHeadlessProject({
                    adobe: {
                        projectId: 'p1',
                        projectName: 'proj',
                        authenticated: true,
                        organization: 'Acme Org',
                        projectTitle: 'Proj',
                        workspace: 'Stage',
                    },
                });
                const result = generateAgentsMd(project, STACKS);

                // Shipped behavior: the extension targets the org PER OPERATION
                // (no shared global to clobber); concurrent windows stay isolated.
                expect(result).toMatch(/per operation/i);
                expect(result).toContain('ORG_MISMATCH');
                expect(result).toMatch(/do not retry/i);
            });

            it('tells the agent to set its target before Adobe ops (select_org → … → select_workspace)', () => {
                const project = makeHeadlessProject({
                    adobe: {
                        projectId: 'p1',
                        projectName: 'proj',
                        authenticated: true,
                        organization: 'Acme Org',
                        projectTitle: 'Proj',
                        workspace: 'Stage',
                    },
                });
                const result = generateAgentsMd(project, STACKS);

                expect(result).toContain('select_org');
                expect(result).toContain('select_workspace');
            });

            it('no longer frames org context as a shared global setting', () => {
                const project = makeHeadlessProject({
                    adobe: {
                        projectId: 'p1',
                        projectName: 'proj',
                        authenticated: true,
                        organization: 'Acme Org',
                        projectTitle: 'Proj',
                        workspace: 'Stage',
                    },
                });
                const result = generateAgentsMd(project, STACKS);

                expect(result).not.toMatch(/global and shared/i);
                expect(result).not.toMatch(/process-wide setting shared/i);
            });
        });

        describe('package name', () => {
            it('includes the package display name for isle5', () => {
                const project = makeEdsProject({ selectedPackage: 'isle5' });
                const result = generateAgentsMd(project, STACKS);

                expect(result).toContain('Isle5');
            });

            it('includes the package display name for citisignal', () => {
                const project = makeHeadlessProject({ selectedPackage: 'citisignal' });
                const result = generateAgentsMd(project, STACKS);

                expect(result).toContain('CitiSignal');
            });
        });

        describe('block libraries', () => {
            it('lists installed block libraries with name, source URL, and block IDs', () => {
                const installedLibraries: InstalledBlockLibrary[] = [
                    {
                        name: 'Isle5 Block Collection',
                        source: { owner: 'stephen-garner-adobe', repo: 'isle5', branch: 'main' },
                        commitSha: 'abc123',
                        blockIds: ['hero', 'carousel', 'newsletter'],
                        installedAt: '2026-01-01T00:00:00Z',
                    },
                ];
                const project = makeEdsProject({ installedBlockLibraries: installedLibraries });
                const result = generateAgentsMd(project, STACKS);

                expect(result).toContain('Isle5 Block Collection');
                expect(result).toContain('https://github.com/stephen-garner-adobe/isle5');
                expect(result).toContain('hero');
                expect(result).toContain('carousel');
            });

            it('labels custom block libraries as custom', () => {
                const customLibs: CustomBlockLibrary[] = [
                    {
                        name: 'My Custom Blocks',
                        source: { owner: 'org', repo: 'my-blocks', branch: 'main' },
                    },
                ];
                const installedLibraries: InstalledBlockLibrary[] = [
                    {
                        name: 'My Custom Blocks',
                        source: { owner: 'org', repo: 'my-blocks', branch: 'main' },
                        commitSha: 'def456',
                        blockIds: ['my-hero'],
                        installedAt: '2026-01-01T00:00:00Z',
                    },
                ];
                const project = makeEdsProject({
                    customBlockLibraries: customLibs,
                    installedBlockLibraries: installedLibraries,
                });
                const result = generateAgentsMd(project, STACKS);

                expect(result).toContain('custom');
                expect(result).toContain('My Custom Blocks');
            });

            it('does not include Block Libraries section for headless projects', () => {
                const project = makeHeadlessProject();
                const result = generateAgentsMd(project, STACKS);

                expect(result).not.toContain('Block Libraries');
            });

            it('does not include Block Libraries section when no libraries installed', () => {
                const project = makeEdsProject({ installedBlockLibraries: [] });
                const result = generateAgentsMd(project, STACKS);

                expect(result).not.toContain('Block Libraries');
            });

            it('marks block libraries as read-only sources', () => {
                const installedLibraries: InstalledBlockLibrary[] = [
                    {
                        name: 'Isle5 Block Collection',
                        source: { owner: 'stephen-garner-adobe', repo: 'isle5', branch: 'main' },
                        commitSha: 'abc123',
                        blockIds: ['hero'],
                        installedAt: '2026-01-01T00:00:00Z',
                    },
                ];
                const project = makeEdsProject({ installedBlockLibraries: installedLibraries });
                const result = generateAgentsMd(project, STACKS);

                expect(result).toMatch(/read-only sources/i);
                expect(result).toMatch(/library promotion is a planned future/i);
            });
        });
    });
});
