/**
 * Jest config for the FOCUSED mutation run — one module at a time.
 *
 * The sample (`jest.pl22.config.js`) runs twelve modules' tests and takes ~16
 * minutes. That is the right cadence for a release check and the wrong one for
 * working a module: killing a survivor and re-measuring should cost minutes.
 *
 * `testMatch` here and `mutate` in `stryker.focus.config.json` must agree.
 * `tests/sop/mutation-config-pairing.test.ts` fails the build when they do not, because
 * a run where they DID disagree reported 0% for seven modules and finished in 19
 * seconds — which reads as a devastating result and was a run that never executed the
 * tests.
 *
 * MOVING TO THE NEXT MODULE is one command, and both files are written from it:
 *
 *     node scripts/focusModule.mjs src/features/eds/services/siteTools.ts
 *
 * This file's suite list is GENERATED by that script. Editing it by hand is what the
 * script exists to stop: the instruction used to be "edit both files together", which
 * is a rule you follow until the night you do not.
 */
const base = require('./jest.config.js');

const project = base.projects.find((p) => p.displayName === 'node');

module.exports = {
    ...project,
    displayName: 'stryker-focus',
    // LISTED, not globbed: `mutation-config-pairing` verifies each named path
    // exists, and a glob is not a path it can check.
    // GENERATED by scripts/focusModule.mjs — re-run it rather than editing by hand.
    // Environment: node
    testMatch: [
        '**/tests/features/project-creation/services/aiBundle/globalMcpRegistration.test.ts',
    ],
};
