/**
 * Jest config for the FOCUSED mutation run — one module at a time.
 *
 * The sample (`jest.pl22.config.js`) runs twelve modules' tests and takes ~16
 * minutes. That is the right cadence for a release check and the wrong one for
 * working a module: killing a survivor and re-measuring should cost minutes.
 *
 * `testMatch` here and `mutate` in `stryker.focus.config.json` must agree.
 * `tests/sop/mutation-config-pairing.test.ts` fails the build when they do not, because
 * a run where they DID disagree reported 0% for seven modules and finished in 19
 * seconds — which reads as a devastating result and was a run that never executed the
 * tests.
 *
 * MOVING TO THE NEXT MODULE is one command, and both files are written from it:
 *
 *     node scripts/focusModule.mjs src/features/eds/services/siteTools.ts
 *
 * This file's suite list is GENERATED by that script. Editing it by hand is what the
 * script exists to stop: the instruction used to be "edit both files together", which
 * is a rule you follow until the night you do not.
 */
const base = require('./jest.config.js');

const react = base.projects.find((p) => p.displayName === 'react');
const node = base.projects.find((p) => p.displayName === 'node');

// A transform entry the react project does not already cover: its key does not
// match a .ts or .tsx filename, so taking it cannot displace the tsx-aware one.
const isNonTypeScript = ([pattern]) =>
    !new RegExp(pattern).test('x.ts') && !new RegExp(pattern).test('x.tsx');

module.exports = {
    ...react,
    displayName: 'stryker-focus',
    // GENERATED by scripts/focusModule.mjs — re-run it rather than editing by hand.
    // Environment: jsdom for BOTH sets — this focus has suites in each, and Stryker
    // cannot run two jest projects in one measurement.
    transform: {
        ...react.transform,
        ...Object.fromEntries(Object.entries(node.transform).filter(isNonTypeScript)),
    },
    moduleFileExtensions: [
        ...new Set([...react.moduleFileExtensions, ...node.moduleFileExtensions]),
    ],
    // React's entries win where both name the same specifier; node's add the
    // aliases (@/commands, @/mcp-server) the react project never needed.
    moduleNameMapper: { ...node.moduleNameMapper, ...react.moduleNameMapper },
    transformIgnorePatterns: node.transformIgnorePatterns,
    testMatch: [
        '**/tests/core/utils/loadingHTML.test.ts',
        '**/tests/core/vscode/progressRegister.test.ts',
        '**/tests/core/ui/hooks/useDebouncedLoading.test.ts',
        '**/tests/core/ui/hooks/useFocusOnMount.test.tsx',
        '**/tests/core/ui/hooks/useVSCodeRequest.test.ts',
    ],
};
