/**
 * Writes one component's `.env` (or `.env.local` for Next.js) from the registry.
 *
 * The single `.env` writer: project creation calls it directly, and
 * `envFileRegeneration.ts` calls it for an existing project, so both produce the
 * same file. Which keys and values go in is decided in `envVarResolution.ts`.
 */

import { promises as fsPromises } from 'fs';
import * as path from 'path';
import {
    resolveComponentEnvVars,
    resolveEnvVarValue,
    resolveFromComponentConfigs,
    type EnvGenerationContext,
} from './envVarResolution';
import { formatGroupName } from './formatters';
import { normalizeIfUrl } from '@/core/validation/Validator';
import type { TransformedComponentDefinition, EnvVarDefinition } from '@/types/components';

/**
 * Group env var definitions by their group field.
 */
function groupEnvVarsBySection(vars: EnvVarDefinition[]): Map<string, EnvVarDefinition[]> {
    const groups = new Map<string, EnvVarDefinition[]>();
    for (const envVar of vars) {
        const group = envVar.group || 'general';
        if (!groups.has(group)) {
            groups.set(group, []);
        }
        groups.get(group)?.push(envVar);
    }
    return groups;
}

/**
 * Append env var lines (description comment + key=value) to the output.
 */
function appendEnvVarLines(lines: string[], envVar: EnvVarDefinition, value: string): void {
    if (envVar.description) {
        lines.push(`# ${envVar.description}`);
    }
    const normalizedValue = normalizeIfUrl(value);
    lines.push(`${envVar.key}=${normalizedValue || ''}`);
}

/**
 * Generate component-specific .env file using EnvGenerationContext
 *
 * This function pulls values from ALL componentConfigs, not just the component's own config.
 * This enables cross-boundary value sharing (e.g., backend config values in frontend .env).
 *
 * @param componentPath - Path to the component directory
 * @param componentId - ID of the component
 * @param componentDef - Component definition from components.json
 * @param context - Context providing registry, configs, and accessors
 */
export async function generateComponentEnvFile(
    componentPath: string,
    componentId: string,
    componentDef: TransformedComponentDefinition,
    context: EnvGenerationContext,
): Promise<void> {
    const lines: string[] = [
        `# ${componentDef.name} - Environment Configuration`,
        '# Generated by Demo Builder',
        '# Generated: ' + new Date().toISOString(),
        '',
    ];

    // Get all relevant env var keys (component vars + service vars)
    const allKeys = resolveComponentEnvVars(componentDef, context.registry, context.getBackendId());

    // Helper to get value from config
    const getConfigValue = (key: string): string | undefined =>
        resolveFromComponentConfigs(key, context);

    // Build EnvVarDefinition objects by looking up from shared dictionary
    const sharedEnvVars = context.getEnvVarDefinitions();
    const varsByKey = new Map<string, EnvVarDefinition>();

    // Collect all explicitly required vars, deduplicating by key (first one wins)
    for (const key of allKeys) {
        if (!varsByKey.has(key)) {
            const envVar = sharedEnvVars[key];
            if (envVar) {
                varsByKey.set(key, {
                    key,
                    ...envVar,
                    usedBy: [componentId],
                });
            }
        }
    }

    // Compute derived values using declarative metadata (derivedFrom)
    const derivedValues = new Map<string, string>();

    for (const [key, envVar] of varsByKey.entries()) {
        if (envVar.derivedFrom && envVar.derivedFrom.length > 0) {
            // Try each source in order, use first non-empty value
            for (const sourceKey of envVar.derivedFrom) {
                const sourceValue = getConfigValue(sourceKey);
                if (sourceValue) {
                    derivedValues.set(key, sourceValue);
                    context.logger.debug(
                        `[Env Generator] Computed ${key} from ${sourceKey}: ${sourceValue}`,
                    );
                    break;
                }
            }
        }
    }

    // Convert deduplicated map to array
    const relevantVars = Array.from(varsByKey.values());

    if (relevantVars.length > 0) {
        const groups = groupEnvVarsBySection(relevantVars);

        for (const [groupName, vars] of groups.entries()) {
            lines.push(`# ${formatGroupName(groupName)}`);

            for (const envVar of vars) {
                const value = resolveEnvVarValue(envVar, derivedValues, context);
                appendEnvVarLines(lines, envVar, value);
            }

            lines.push('');
        }
    }

    // Determine filename based on component type
    // Next.js uses .env.local, others use .env
    const envFileName = componentDef.id.includes('nextjs') ? '.env.local' : '.env';
    const envFilePath = path.join(componentPath, envFileName);

    // Write the file
    await fsPromises.writeFile(envFilePath, lines.join('\n'));

    context.logger.debug(`[Project Creation] Created ${envFileName} for ${componentDef.name}`);
}
