/**
 * Unit tests for envFileGenerator
 * Tests .env file generation, variable formatting, comment preservation, and validation
 */

import { promises as fsPromises } from 'fs';
import * as path from 'path';
import { generateComponentEnvFile } from '@/features/project-creation/helpers/envFileGenerator';
import { TransformedComponentDefinition, EnvVarDefinition } from '@/types/components';
import type { Logger } from '@/types/logger';

// Mock fs promises
jest.mock('fs', () => ({
    promises: {
        writeFile: jest.fn(),
    },
}));

// Mock formatters
jest.mock('@/features/project-creation/helpers/formatters', () => ({
    formatGroupName: (group: string) => group.split('-').map(word =>
        word.charAt(0).toUpperCase() + word.slice(1)
    ).join(' '),
}));

describe('envFileGenerator', () => {
    let mockLogger: Logger;
    const mockComponentPath = '/test/path/component';

    beforeEach(() => {
        jest.clearAllMocks();
        mockLogger = {
            info: jest.fn(),
            error: jest.fn(),
            warn: jest.fn(),
            debug: jest.fn(),
        };
    });

    describe('generateComponentEnvFile', () => {
        it('should generate basic .env file with header', async () => {
            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {
                    envVars: [],
                },
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                mockComponentPath,
                'test-component',
                componentDef,
                {},
                mockLogger,
            );

            expect(fsPromises.writeFile).toHaveBeenCalledWith(
                path.join(mockComponentPath, '.env'),
                expect.stringContaining('# Test Component - Environment Configuration'),
            );
            expect(fsPromises.writeFile).toHaveBeenCalledWith(
                expect.any(String),
                expect.stringContaining('# Generated by Demo Builder'),
            );
        });

        it('should use .env.local for Next.js components', async () => {
            const componentDef: TransformedComponentDefinition = {
                id: 'nextjs-storefront',
                name: 'Next.js Storefront',
                type: 'frontend',
                configuration: {
                    envVars: [],
                },
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                mockComponentPath,
                'nextjs-storefront',
                componentDef,
                {},
                mockLogger,
            );

            expect(fsPromises.writeFile).toHaveBeenCalledWith(
                path.join(mockComponentPath, '.env.local'),
                expect.any(String),
            );
            expect(mockLogger.info).toHaveBeenCalledWith(
                expect.stringContaining('.env.local'),
            );
        });

        it('should filter environment variables by component', async () => {
            const envVars: EnvVarDefinition[] = [
                {
                    key: 'USED_VAR',
                    label: 'Used Var',
                    type: 'text',
                    description: 'Used by this component',
                    usedBy: ['test-component'],
                    default: 'value1',
                },
                {
                    key: 'UNUSED_VAR',
                    label: 'Unused Var',
                    type: 'text',
                    description: 'Used by different component',
                    usedBy: ['other-component'],
                    default: 'value2',
                },
            ];

            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {
                    envVars,
                },
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                mockComponentPath,
                'test-component',
                componentDef,
                {},
                mockLogger,
            );

            const [[, content]] = (fsPromises.writeFile as jest.Mock).mock.calls;
            expect(content).toContain('USED_VAR=value1');
            expect(content).not.toContain('UNUSED_VAR');
        });

        it('should group variables by group name', async () => {
            const envVars: EnvVarDefinition[] = [
                {
                    key: 'API_KEY',
                    label: 'API Key',
                    type: 'password',
                    description: 'API key',
                    usedBy: ['test-component'],
                    group: 'api-config',
                },
                {
                    key: 'DB_HOST',
                    label: 'DB Host',
                    type: 'text',
                    description: 'Database host',
                    usedBy: ['test-component'],
                    group: 'database',
                },
                {
                    key: 'API_URL',
                    label: 'API URL',
                    type: 'url',
                    description: 'API URL',
                    usedBy: ['test-component'],
                    group: 'api-config',
                },
            ];

            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {
                    envVars,
                },
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                mockComponentPath,
                'test-component',
                componentDef,
                {},
                mockLogger,
            );

            const [[, content]] = (fsPromises.writeFile as jest.Mock).mock.calls;
            expect(content).toContain('# Api Config');
            expect(content).toContain('# Database');
        });

        it('should use "general" as default group', async () => {
            const envVars: EnvVarDefinition[] = [
                {
                    key: 'VAR_WITHOUT_GROUP',
                    label: 'Var Without Group',
                    type: 'text',
                    description: 'Variable without group',
                    usedBy: ['test-component'],
                },
            ];

            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {
                    envVars,
                },
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                mockComponentPath,
                'test-component',
                componentDef,
                {},
                mockLogger,
            );

            const [[, content]] = (fsPromises.writeFile as jest.Mock).mock.calls;
            expect(content).toContain('# General');
        });

        it('should prioritize MESH_ENDPOINT from runtime config', async () => {
            const envVars: EnvVarDefinition[] = [
                {
                    key: 'MESH_ENDPOINT',
                    label: 'Mesh Endpoint',
                    type: 'url',
                    description: 'Mesh endpoint',
                    usedBy: ['test-component'],
                    default: 'default-endpoint',
                },
            ];

            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {
                    envVars,
                },
            } as TransformedComponentDefinition;

            const config = {
                apiMesh: {
                    endpoint: 'https://runtime-endpoint.adobe.io/graphql',
                },
            };

            await generateComponentEnvFile(
                mockComponentPath,
                'test-component',
                componentDef,
                config,
                mockLogger,
            );

            const [[, content]] = (fsPromises.writeFile as jest.Mock).mock.calls;
            expect(content).toContain('MESH_ENDPOINT=https://runtime-endpoint.adobe.io/graphql');
        });

        it('should use user-provided values from componentConfigs', async () => {
            const envVars: EnvVarDefinition[] = [
                {
                    key: 'API_KEY',
                    label: 'API Key',
                    type: 'password',
                    description: 'API key',
                    usedBy: ['test-component'],
                    default: 'default-key',
                },
            ];

            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {
                    envVars,
                },
            } as TransformedComponentDefinition;

            const config = {
                componentConfigs: {
                    'test-component': {
                        API_KEY: 'user-provided-key',
                    },
                },
            };

            await generateComponentEnvFile(
                mockComponentPath,
                'test-component',
                componentDef,
                config,
                mockLogger,
            );

            const [[, content]] = (fsPromises.writeFile as jest.Mock).mock.calls;
            expect(content).toContain('API_KEY=user-provided-key');
        });

        it('should search all components for user-provided values', async () => {
            const envVars: EnvVarDefinition[] = [
                {
                    key: 'SHARED_VAR',
                    label: 'Shared Var',
                    type: 'text',
                    description: 'Shared variable',
                    usedBy: ['test-component'],
                    default: 'default-value',
                },
            ];

            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {
                    envVars,
                },
            } as TransformedComponentDefinition;

            const config = {
                componentConfigs: {
                    'other-component': {
                        SHARED_VAR: 'value-from-other-component',
                    },
                },
            };

            await generateComponentEnvFile(
                mockComponentPath,
                'test-component',
                componentDef,
                config,
                mockLogger,
            );

            const [[, content]] = (fsPromises.writeFile as jest.Mock).mock.calls;
            expect(content).toContain('SHARED_VAR=value-from-other-component');
        });

        it('should fall back to default value if no user value', async () => {
            const envVars: EnvVarDefinition[] = [
                {
                    key: 'DEFAULT_VAR',
                    label: 'Default Var',
                    type: 'text',
                    description: 'Variable with default',
                    usedBy: ['test-component'],
                    default: 'default-value',
                },
            ];

            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {
                    envVars,
                },
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                mockComponentPath,
                'test-component',
                componentDef,
                {},
                mockLogger,
            );

            const [[, content]] = (fsPromises.writeFile as jest.Mock).mock.calls;
            expect(content).toContain('DEFAULT_VAR=default-value');
        });

        it('should use empty string if no default or user value', async () => {
            const envVars: EnvVarDefinition[] = [
                {
                    key: 'EMPTY_VAR',
                    label: 'Empty Var',
                    type: 'text',
                    description: 'Variable without default',
                    usedBy: ['test-component'],
                },
            ];

            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {
                    envVars,
                },
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                mockComponentPath,
                'test-component',
                componentDef,
                {},
                mockLogger,
            );

            const [[, content]] = (fsPromises.writeFile as jest.Mock).mock.calls;
            expect(content).toContain('EMPTY_VAR=');
        });

        it('should include descriptions as comments', async () => {
            const envVars: EnvVarDefinition[] = [
                {
                    key: 'DOCUMENTED_VAR',
                    label: 'Documented Var',
                    type: 'text',
                    description: 'This is a documented variable',
                    usedBy: ['test-component'],
                    default: 'value',
                },
            ];

            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {
                    envVars,
                },
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                mockComponentPath,
                'test-component',
                componentDef,
                {},
                mockLogger,
            );

            const [[, content]] = (fsPromises.writeFile as jest.Mock).mock.calls;
            expect(content).toContain('# This is a documented variable');
            expect(content).toContain('DOCUMENTED_VAR=value');
        });

        it('should handle numeric and boolean values', async () => {
            const envVars: EnvVarDefinition[] = [
                {
                    key: 'PORT',
                    label: 'Port',
                    type: 'number',
                    description: 'Port number',
                    usedBy: ['test-component'],
                    default: 3000,
                },
                {
                    key: 'ENABLED',
                    label: 'Enabled',
                    type: 'boolean',
                    description: 'Feature enabled',
                    usedBy: ['test-component'],
                    default: true,
                },
            ];

            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {
                    envVars,
                },
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                mockComponentPath,
                'test-component',
                componentDef,
                {},
                mockLogger,
            );

            const [[, content]] = (fsPromises.writeFile as jest.Mock).mock.calls;
            expect(content).toContain('PORT=3000');
            expect(content).toContain('ENABLED=true');
        });

        it('should handle components with no environment variables', async () => {
            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {},
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                mockComponentPath,
                'test-component',
                componentDef,
                {},
                mockLogger,
            );

            const [[, content]] = (fsPromises.writeFile as jest.Mock).mock.calls;
            expect(content).toContain('# Test Component - Environment Configuration');
            expect(mockLogger.info).toHaveBeenCalled();
        });

        it('should include ISO timestamp in generated header', async () => {
            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {
                    envVars: [],
                },
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                mockComponentPath,
                'test-component',
                componentDef,
                {},
                mockLogger,
            );

            const [[, content]] = (fsPromises.writeFile as jest.Mock).mock.calls;
            expect(content).toMatch(/# Generated: \d{4}-\d{2}-\d{2}T/);
        });
    });
});
