/**
 * Unit tests for how one env var's VALUE is decided, and what the finished .env
 * file looks like line for line.
 *
 * The priority order — derived value, mesh endpoint, any component config,
 * declared default, empty — is only visible in the bytes written, so these tests
 * assert the whole file rather than a substring: a header, one comment per
 * described var, and a blank line closing each group.
 */

import { promises as fsPromises } from 'fs';
import {
    generateComponentEnvFile,
    regenerateProjectEnvFiles,
} from '@/features/project-creation/helpers/envFileGenerator';
import type { ComponentConfigs } from '@/types/components';
import {
    ComponentRegistry,
    EnvVarDefinition,
    TransformedComponentDefinition,
} from '@/types/components';
import {
    createMockLogger,
    createMockSetupContext,
    TEST_COMPONENT_PATH,
} from './envFileGenerator.testUtils';
import { createMockProject } from '../../../helpers/projectFake';
import { createMockSecretStorage } from '../../../helpers/secretStorageFake';

jest.mock('fs', () => ({ promises: { writeFile: jest.fn() } }));
jest.mock('@/features/project-creation/helpers/formatters', () => ({
    formatGroupName: (g: string) => g,
}));

const ENV_VARS: Record<string, Omit<EnvVarDefinition, 'key'>> = {
    PLAIN: { label: 'Plain', type: 'text', description: 'A described var' },
    NO_DESCRIPTION: { label: 'Bare', type: 'text' },
    WITH_DEFAULT: { label: 'Defaulted', type: 'text', default: 'the-default' },
    MESH_ENDPOINT: { label: 'Mesh', type: 'url' },
    GROUPED: { label: 'Grouped', type: 'text', group: 'api' },
    DERIVED: { label: 'Derived', type: 'text', derivedFrom: ['SOURCE_A', 'SOURCE_B'] },
    SOURCE_A: { label: 'Source A', type: 'text' },
    SOURCE_B: { label: 'Source B', type: 'text' },
    ACCS_WEBSITE_CODE: { label: 'Website', type: 'text' },
};

/** The written file, split into lines with the volatile timestamp line removed. */
function writtenLines(): string[] {
    const body = (fsPromises.writeFile as jest.Mock).mock.calls[0][1] as string;
    return body.split('\n').filter((line) => !line.startsWith('# Generated: '));
}

function componentFor(required: string[]): TransformedComponentDefinition {
    return {
        id: 'test-component',
        name: 'Test Component',
        type: 'frontend',
        configuration: { requiredEnvVars: required, optionalEnvVars: [] },
    } as TransformedComponentDefinition;
}

async function envFor(
    required: string[],
    options: { componentConfigs?: ComponentConfigs; backend?: string; meshEndpoint?: string } = {}
): Promise<void> {
    const context = createMockSetupContext({
        registry: { envVars: ENV_VARS },
        config: {
            projectName: 'test-project',
            componentConfigs: options.componentConfigs,
            ...(options.backend ? { components: { backend: options.backend } } : {}),
        },
        project: createMockProject({
            appBuilderComponents: options.meshEndpoint
                ? {
                      mesh: {
                          kind: 'mesh',
                          status: 'deployed',
                          source: { owner: '', repo: '' },
                          endpoint: options.meshEndpoint,
                      },
                  }
                : undefined,
        }),
    });
    await generateComponentEnvFile(
        TEST_COMPONENT_PATH,
        'test-component',
        componentFor(required),
        context
    );
}

describe('the shape of a generated .env', () => {
    beforeEach(() => {
        jest.clearAllMocks();
    });

    it('writes header, a blank line, the group, its vars, and a closing blank line', async () => {
        await envFor(['PLAIN']);

        expect(writtenLines()).toEqual([
            '# Test Component - Environment Configuration',
            '# Generated by Demo Builder',
            '',
            '# general',
            '# A described var',
            'PLAIN=',
            '',
        ]);
    });

    it('omits the comment line for a var that declares no description', async () => {
        await envFor(['NO_DESCRIPTION']);

        expect(writtenLines()).toEqual([
            '# Test Component - Environment Configuration',
            '# Generated by Demo Builder',
            '',
            '# general',
            'NO_DESCRIPTION=',
            '',
        ]);
    });

    it('closes each group with its own blank line', async () => {
        await envFor(['PLAIN', 'GROUPED']);

        expect(writtenLines()).toEqual([
            '# Test Component - Environment Configuration',
            '# Generated by Demo Builder',
            '',
            '# general',
            '# A described var',
            'PLAIN=',
            '',
            '# api',
            'GROUPED=',
            '',
        ]);
    });

    it('writes only the header for a component that declares nothing', async () => {
        await envFor([]);

        expect(writtenLines()).toEqual([
            '# Test Component - Environment Configuration',
            '# Generated by Demo Builder',
            '',
        ]);
    });

    it('skips a required key the registry dictionary does not define', async () => {
        await envFor(['NOT_IN_REGISTRY', 'PLAIN']);

        expect(writtenLines()).toEqual([
            '# Test Component - Environment Configuration',
            '# Generated by Demo Builder',
            '',
            '# general',
            '# A described var',
            'PLAIN=',
            '',
        ]);
    });
});

describe('which value a var gets', () => {
    beforeEach(() => {
        jest.clearAllMocks();
    });

    it('falls back to the declared default when nothing supplies a value', async () => {
        await envFor(['WITH_DEFAULT']);

        expect(writtenLines()).toContain('WITH_DEFAULT=the-default');
    });

    it('lets a component config beat the declared default', async () => {
        await envFor(['WITH_DEFAULT'], {
            componentConfigs: { any: { WITH_DEFAULT: 'from-config' } },
        });

        expect(writtenLines()).toContain('WITH_DEFAULT=from-config');
    });

    it('writes an empty assignment for a var with neither a default nor a config value', async () => {
        await envFor(['PLAIN']);

        expect(writtenLines()).toContain('PLAIN=');
    });

    it('keeps a blank config value rather than falling back to the default', async () => {
        await envFor(['WITH_DEFAULT'], { componentConfigs: { any: { WITH_DEFAULT: '' } } });

        expect(writtenLines()).toContain('WITH_DEFAULT=');
    });

    it('reads past a component that does not define the key', async () => {
        await envFor(['PLAIN'], {
            componentConfigs: { first: { OTHER: 'x' }, second: { PLAIN: 'found-later' } },
        });

        expect(writtenLines()).toContain('PLAIN=found-later');
    });

    it('reads past a component whose config entry is missing entirely', async () => {
        await envFor(['PLAIN'], {
            componentConfigs: {
                ghost: undefined,
                second: { PLAIN: 'found-later' },
            } as unknown as ComponentConfigs,
        });

        expect(writtenLines()).toContain('PLAIN=found-later');
    });

    it('resolves a backend-owned key with a backend selected and no component configs at all', async () => {
        await envFor(['ACCS_WEBSITE_CODE'], { backend: 'adobe-commerce-accs' });

        expect(writtenLines()).toContain('ACCS_WEBSITE_CODE=');
    });

    it('takes MESH_ENDPOINT from the deployed mesh', async () => {
        await envFor(['MESH_ENDPOINT'], {
            meshEndpoint: 'https://mesh.example/graphql',
            componentConfigs: { any: { MESH_ENDPOINT: 'https://stale' } },
        });

        expect(writtenLines()).toContain('MESH_ENDPOINT=https://mesh.example/graphql');
    });

    it('writes MESH_ENDPOINT empty when no mesh is deployed', async () => {
        await envFor(['MESH_ENDPOINT']);

        expect(writtenLines()).toContain('MESH_ENDPOINT=');
    });
});

describe('derivedFrom', () => {
    beforeEach(() => {
        jest.clearAllMocks();
    });

    it('takes the derived value from the first source that has one', async () => {
        await envFor(['DERIVED'], {
            componentConfigs: { any: { SOURCE_A: 'from-a', SOURCE_B: 'from-b' } },
        });

        expect(writtenLines()).toContain('DERIVED=from-a');
    });

    it('moves to the next source when the first is empty', async () => {
        await envFor(['DERIVED'], {
            componentConfigs: { any: { SOURCE_A: '', SOURCE_B: 'from-b' } },
        });

        expect(writtenLines()).toContain('DERIVED=from-b');
    });

    it('leaves the var empty when no source has a value', async () => {
        await envFor(['DERIVED'], { componentConfigs: { any: { OTHER: 'x' } } });

        expect(writtenLines()).toContain('DERIVED=');
    });

    it('beats a direct config value for the derived key itself', async () => {
        await envFor(['DERIVED'], {
            componentConfigs: { any: { DERIVED: 'direct', SOURCE_A: 'from-a' } },
        });

        expect(writtenLines()).toContain('DERIVED=from-a');
    });
});

describe('regeneration reads the backend the project recorded', () => {
    const secretsFake = createMockSecretStorage().secrets;

    const registry = {
        envVars: ENV_VARS,
        components: { frontends: [componentFor(['ACCS_WEBSITE_CODE'])] },
        services: {},
    } as unknown as ComponentRegistry;

    beforeEach(() => {
        jest.clearAllMocks();
    });

    it('prefers the backend copy of a scope key over a stale duplicate listed first', async () => {
        await regenerateProjectEnvFiles(
            createMockProject({
                path: '/p',
                componentSelections: { backend: 'adobe-commerce-accs' },
                componentInstances: {
                    'test-component': {
                        id: 'test-component',
                        name: 'test-component',
                        status: 'ready',
                        path: '/p/component',
                    },
                },
                componentConfigs: {
                    'eds-accs-mesh': { ACCS_WEBSITE_CODE: 'stale-base' },
                    'adobe-commerce-accs': { ACCS_WEBSITE_CODE: 'citisignal' },
                },
            }),
            registry,
            createMockLogger(),
            secretsFake
        );

        expect(writtenLines()).toContain('ACCS_WEBSITE_CODE=citisignal');
    });

    it('skips a componentInstances entry with no instance recorded against it', async () => {
        await regenerateProjectEnvFiles(
            createMockProject({
                path: '/p',
                componentInstances: {
                    ghost: undefined,
                } as unknown as NonNullable<
                    ReturnType<typeof createMockProject>['componentInstances']
                >,
            }),
            registry,
            createMockLogger(),
            secretsFake
        );

        expect(fsPromises.writeFile).not.toHaveBeenCalled();
    });
});
