/**
 * Unit tests for envFileGenerator - Basic generation and file naming
 * Tests header generation, .env.local handling for Next.js, and edge cases
 */

import { promises as fsPromises } from 'fs';
import * as path from 'path';
import { generateComponentEnvFile } from '@/features/project-creation/helpers/envFileGenerator';
import { TransformedComponentDefinition } from '@/types/components';
import type { Logger } from '@/types/logger';
import {
    createMockLogger,
    sharedEnvVars,
    TEST_COMPONENT_PATH,
} from './envFileGenerator.testUtils';

// Mock fs promises
jest.mock('fs', () => ({
    promises: {
        writeFile: jest.fn(),
    },
}));

// Mock formatters
jest.mock('@/features/project-creation/helpers/formatters', () => ({
    formatGroupName: (group: string) => group.split('-').map(word =>
        word.charAt(0).toUpperCase() + word.slice(1)
    ).join(' '),
}));

describe('envFileGenerator - Basic Generation', () => {
    let mockLogger: Logger;

    beforeEach(() => {
        jest.clearAllMocks();
        mockLogger = createMockLogger();
    });

    describe('file generation and headers', () => {
        it('should generate basic .env file with header', async () => {
            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {
                    requiredEnvVars: [],
                    optionalEnvVars: [],
                },
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                TEST_COMPONENT_PATH,
                'test-component',
                componentDef,
                sharedEnvVars,
                {},
                mockLogger,
            );

            expect(fsPromises.writeFile).toHaveBeenCalledWith(
                path.join(TEST_COMPONENT_PATH, '.env'),
                expect.stringContaining('# Test Component - Environment Configuration'),
            );
            expect(fsPromises.writeFile).toHaveBeenCalledWith(
                expect.any(String),
                expect.stringContaining('# Generated by Demo Builder'),
            );
        });

        it('should include ISO timestamp in generated header', async () => {
            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {
                    requiredEnvVars: [],
                    optionalEnvVars: [],
                },
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                TEST_COMPONENT_PATH,
                'test-component',
                componentDef,
                sharedEnvVars,
                {},
                mockLogger,
            );

            const [[, content]] = (fsPromises.writeFile as jest.Mock).mock.calls;
            expect(content).toMatch(/# Generated: \d{4}-\d{2}-\d{2}T/);
        });

        it('should handle components with no environment variables', async () => {
            const componentDef: TransformedComponentDefinition = {
                id: 'test-component',
                name: 'Test Component',
                type: 'frontend',
                configuration: {},
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                TEST_COMPONENT_PATH,
                'test-component',
                componentDef,
                sharedEnvVars,
                {},
                mockLogger,
            );

            const [[, content]] = (fsPromises.writeFile as jest.Mock).mock.calls;
            expect(content).toContain('# Test Component - Environment Configuration');
            expect(mockLogger.debug).toHaveBeenCalled();
        });
    });

    describe('Next.js-specific handling', () => {
        it('should use .env.local for Next.js components', async () => {
            const componentDef: TransformedComponentDefinition = {
                id: 'nextjs-storefront',
                name: 'Next.js Storefront',
                type: 'frontend',
                configuration: {
                    requiredEnvVars: [],
                    optionalEnvVars: [],
                },
            } as TransformedComponentDefinition;

            await generateComponentEnvFile(
                TEST_COMPONENT_PATH,
                'nextjs-storefront',
                componentDef,
                sharedEnvVars,
                {},
                mockLogger,
            );

            expect(fsPromises.writeFile).toHaveBeenCalledWith(
                path.join(TEST_COMPONENT_PATH, '.env.local'),
                expect.any(String),
            );
            expect(mockLogger.debug).toHaveBeenCalledWith(
                expect.stringContaining('.env.local'),
            );
        });
    });
});
