/**
 * Bring an integration's clone up to its branch on GitHub, keeping what the SC
 * changed safe.
 *
 * The clone is fast-forwarded, never re-cloned: re-cloning deletes the folder,
 * and with it anything the SC edited there. So local edits refuse the update and
 * name the files; so does a clone with commits the branch does not have. Changes
 * the tooling makes on its own are not edits: `npm install` rewrites
 * `package-lock.json`, and `@adobe/aio-commerce-lib-app`'s postinstall hook
 * regenerates `.generated/` and the `ext.config.yaml` files. Those are put back
 * before the fast-forward, and regenerated by the install that follows it.
 *
 * @module features/app-builder/services/integrationSourceUpdate
 */

/** One git command in the clone's folder. */
export type GitRunner = (
    command: string,
    cwd: string,
) => Promise<{ code: number | null; stdout: string; stderr: string }>;

export interface SourceUpdateResult {
    status: 'updated' | 'current' | 'refused' | 'failed';
    /** Plain-words line for the SC. */
    detail: string;
    /** The commit before and after, when known. */
    from?: string;
    to?: string;
}

/**
 * Branch names this passes to git: interpolated into a shell command, so only
 * this charset, never a leading '-', never '..'.
 */
const SAFE_BRANCH = /^[A-Za-z0-9._/][A-Za-z0-9._/-]*$/;

/** Files the tooling rewrites by itself (see the module note). */
const TOOLING_OWNED = [/^package-lock\.json$/, /(^|\/)\.generated\//, /(^|\/)ext\.config\.yaml$/];

const MAX_NAMED_FILES = 5;
const SHORT_SHA = 7;

/** Paths from `git status --porcelain` (tracked changes only). */
function changedPaths(porcelain: string): string[] {
    return porcelain
        .split('\n')
        .filter((line) => line.trim().length > 0)
        .map((line) => line.slice(3).replace(/^"|"$/g, ''))
        .map((entry) => entry.split(' -> ').pop() ?? entry);
}

function nameFiles(paths: string[]): string {
    const named = paths.slice(0, MAX_NAMED_FILES).join(', ');
    const more = paths.length - MAX_NAMED_FILES;
    return more > 0 ? `${named} and ${more} more` : named;
}

const short = (sha: string): string => sha.slice(0, SHORT_SHA);

/**
 * Fast-forward the clone at `componentPath` to `origin/<branch>`.
 *
 * @returns updated (with the two commits), current, refused (local edits, or a
 *   clone that has moved away from the branch), or failed (git could not run)
 */
export async function fastForwardClone(
    componentPath: string,
    branch: string,
    run: GitRunner,
): Promise<SourceUpdateResult> {
    if (!SAFE_BRANCH.test(branch) || branch.includes('..')) {
        return { status: 'failed', detail: `The branch name "${branch}" cannot be used.` };
    }
    const failed = (step: string, stderr: string): SourceUpdateResult => ({
        status: 'failed',
        detail: `Could not ${step}: ${stderr.trim() || 'git gave no reason'}.`,
    });

    const status = await run('git status --porcelain --untracked-files=no', componentPath);
    if (status.code !== 0) {
        return failed('read the integration folder', status.stderr);
    }
    const changed = changedPaths(status.stdout);
    const edited = changed.filter((file) => !TOOLING_OWNED.some((pattern) => pattern.test(file)));
    if (edited.length > 0) {
        return {
            status: 'refused',
            detail: `The integration folder has changes of its own (${nameFiles(edited)}). Commit or undo them, then update again.`,
        };
    }
    if (changed.length > 0) {
        // Only tooling-owned files differ: put them back so the fast-forward can
        // run; the install that follows writes them again.
        const restore = await run('git checkout -- .', componentPath);
        if (restore.code !== 0) {
            return failed('reset the generated files', restore.stderr);
        }
    }

    const before = await run('git rev-parse HEAD', componentPath);
    if (before.code !== 0) {
        return failed('read the current version', before.stderr);
    }
    const fetched = await run(`git fetch origin ${branch}`, componentPath);
    if (fetched.code !== 0) {
        return failed(`fetch ${branch} from GitHub`, fetched.stderr);
    }
    const after = await run('git rev-parse FETCH_HEAD', componentPath);
    if (after.code !== 0) {
        return failed('read the fetched version', after.stderr);
    }
    const from = before.stdout.trim();
    const to = after.stdout.trim();
    if (from === to) {
        return { status: 'current', detail: 'The integration is already up to date.', from, to };
    }

    // Only a clone that is behind the branch moves: a clone with commits of its
    // own (ahead, or diverged) keeps them. `merge --ff-only` alone would answer
    // success for a clone that is ahead.
    const behind = await run('git merge-base --is-ancestor HEAD FETCH_HEAD', componentPath);
    const merged = behind.code === 0 ? await run('git merge --ff-only FETCH_HEAD', componentPath) : behind;
    if (merged.code !== 0) {
        return {
            status: 'refused',
            detail: `The integration folder has commits that ${branch} on GitHub does not, so it cannot be updated in place.`,
            from,
            to,
        };
    }
    return {
        status: 'updated',
        detail: `Updated the integration from ${short(from)} to ${short(to)}.`,
        from,
        to,
    };
}
