/**
 * Controls for the transcript parser.
 *
 * The parser is the whole instrument, and this repo has shipped a broken
 * extractor before: `ai-coverage-scan`'s `scan.sh` ran a regex that counted
 * nested object keys as handlers for weeks, while the correct extractor sat
 * unused beside it with its own passing self-test. So the entry point runs these
 * before trusting any number, and a failure exits non-zero.
 *
 * Two of the checks are PRIVACY assertions rather than correctness ones: an
 * argument value and a result body are planted in the fixture, and neither may
 * survive into anything the parser retains.
 */

import fs from 'fs';
import os from 'os';
import path from 'path';
import {
    parseTranscript,
    emptyAggregate,
    taskCost,
    isRealPrompt,
    encodeCwd,
} from './transcript.mjs';

const SECRET_ARG = '/secret/path.txt';
const SECRET_BODY = 'BOOM-SECRET-BODY';

function fixtureLines() {
    const rec = (o) => JSON.stringify(o);
    return [
        // Synthetic slash-command record — must NOT open a task.
        rec({
            type: 'user',
            timestamp: '2026-01-01T00:00:00Z',
            message: { content: '<command-name>/clear</command-name>' },
        }),
        // A real prompt — opens task 1.
        rec({
            type: 'user',
            timestamp: '2026-01-01T00:00:01Z',
            message: { content: 'do the thing' },
        }),
        rec({
            type: 'assistant',
            timestamp: '2026-01-01T00:00:02Z',
            message: {
                usage: {
                    input_tokens: 10,
                    output_tokens: 5,
                    cache_read_input_tokens: 100,
                    cache_creation_input_tokens: 7,
                    output_tokens_details: { thinking_tokens: 3 },
                },
                content: [
                    { type: 'tool_use', id: 'call_1', name: 'Read', input: { file_path: SECRET_ARG } },
                ],
            },
        }),
        // Error result, then a retry of the same tool.
        rec({
            type: 'user',
            timestamp: '2026-01-01T00:00:03Z',
            message: {
                content: [
                    { type: 'tool_result', tool_use_id: 'call_1', is_error: true, content: SECRET_BODY },
                ],
            },
        }),
        rec({
            type: 'assistant',
            timestamp: '2026-01-01T00:00:04Z',
            attributionMcpServer: 'demo-builder',
            attributionMcpTool: 'list_projects',
            message: {
                usage: { input_tokens: 1, output_tokens: 2 },
                content: [{ type: 'tool_use', name: 'Read', input: { file_path: '/x' } }],
            },
        }),
        rec({
            type: 'user',
            timestamp: '2026-01-01T00:00:05Z',
            message: { content: [{ type: 'tool_result', content: 'ok' }] },
        }),
        // A sidechain turn — counted, and flagged separately.
        rec({
            type: 'assistant',
            timestamp: '2026-01-01T00:00:06Z',
            isSidechain: true,
            message: { usage: { input_tokens: 4, output_tokens: 4 }, content: [] },
        }),
        'this line is not json at all',
        // Second real prompt — opens task 2, this time as a text block.
        rec({
            type: 'user',
            timestamp: '2026-01-01T00:00:07Z',
            message: { content: [{ type: 'text', text: 'second task' }] },
        }),
        rec({
            type: 'assistant',
            timestamp: '2026-01-01T00:00:08Z',
            message: { usage: { input_tokens: 2, output_tokens: 2 }, content: [] },
        }),
    ];
}

/** Parse the fixture and return `{ tasks, agg }`. Exported for the jest suite. */
export async function parseFixture() {
    const tmp = path.join(os.tmpdir(), `trace-selftest-${process.pid}-${Date.now()}.jsonl`);
    fs.writeFileSync(tmp, fixtureLines().join('\n') + '\n');
    const agg = emptyAggregate();
    try {
        const tasks = await parseTranscript(tmp, agg);
        return { tasks, agg };
    } finally {
        fs.unlinkSync(tmp);
    }
}

/** Everything the parser retained, as one string — for the privacy assertions. */
export function retainedText({ tasks, agg }) {
    return JSON.stringify({
        tasks: tasks.map((t) => ({ ...t, toolCounts: [...t.toolCounts] })),
        agg: {
            ...agg,
            toolCalls: [...agg.toolCalls],
            argKeys: [...agg.argKeys].map(([k, v]) => [k, [...v]]),
            mcpTurns: [...agg.mcpTurns],
            toolBytes: [...agg.toolBytes],
        },
    });
}

/** Boundary, cost and path-encoding checks that need no fixture parse. */
function unitChecks() {
    const user = (content) => ({ type: 'user', message: { content } });
    const syntheticRejected = [
        '<command-name>/clear</command-name>',
        '<local-command-stdout>output</local-command-stdout>',
        'Caveat: The messages below were generated by the user',
    ].every((s) => !isRealPrompt(user(s)));

    return [
        ['plain prompt opens a task', isRealPrompt(user('do the thing'))],
        [
            'text-block prompt opens a task',
            isRealPrompt(user([{ type: 'text', text: 'do the thing' }])),
        ],
        ['slash-command plumbing is NOT a task', syntheticRejected],
        ['tool result is NOT a task', !isRealPrompt(user([{ type: 'tool_result', content: 'ok' }]))],
        ['empty prompt is NOT a task', !isRealPrompt(user('   '))],
        [
            'assistant record is NOT a task',
            !isRealPrompt({ type: 'assistant', message: { content: 'hi' } }),
        ],
        [
            'cache reads excluded from billable cost',
            taskCost({
                inputTokens: 10,
                outputTokens: 5,
                cacheCreateTokens: 7,
                cacheReadTokens: 1_000_000,
            }) === 22,
        ],
        [
            'cwd encoding replaces BOTH slashes and dots',
            // Omitting the dot rule yields a plausible path that is wrong, so
            // dot-prefixed dirs silently resolve to nothing.
            encodeCwd('/Users/x/.demo-builder/projects/p') === '-Users-x--demo-builder-projects-p',
        ],
    ];
}

/** The check list, shared by `--self-test` and the jest suite. */
export function checksFor({ tasks, agg }) {
    const t1 = tasks[0];
    const retained = retainedText({ tasks, agg });
    return [
        ...unitChecks(),
        ['two tasks, slash-command excluded', tasks.length === 2],
        ['task 1 counted 3 turns (incl. sidechain)', t1.turns === 3],
        ['sidechain turn flagged separately', t1.sidechainTurns === 1],
        ['cache reads kept out of billable cost', taskCost(t1) === 10 + 5 + 7 + 1 + 2 + 4 + 4],
        ['cache reads recorded', t1.cacheReadTokens === 100],
        ['thinking tokens recorded', t1.thinkingTokens === 3],
        [
            'repeat call detected (2 calls, 1 distinct)',
            t1.toolPath.length === 2 && t1.toolCounts.size === 1,
        ],
        ['error result counted', t1.errors === 1],
        ['malformed line counted, not fatal', agg.malformed === 1],
        ['attributionMcpTool counted as TURNS, not calls', agg.mcpTurns.get('demo-builder/list_projects') === 1],
        ['arg KEYS captured', [...(agg.argKeys.get('Read') ?? [])].join() === 'file_path'],
        [
            'per-tool bytes joined via tool_use id',
            (agg.toolBytes.get('Read')?.sizes ?? []).length === 1 &&
                agg.toolBytes.get('Read').errors === 1,
        ],
        ['PRIVACY: no argument VALUE retained', !retained.includes(SECRET_ARG)],
        ['PRIVACY: no result BODY retained', !retained.includes(SECRET_BODY)],
    ];
}

export async function runSelfTest() {
    const parsed = await parseFixture();
    const checks = checksFor(parsed);
    let failed = 0;
    for (const [name, ok] of checks) {
        console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${name}`);
        if (!ok) failed++;
    }
    console.log(`\n${checks.length - failed}/${checks.length} checks passed`);
    return failed === 0;
}
