/**
 * AI Context Writer
 *
 * Generates the AGENTS.md project context file for AI agents (Claude Code, Cursor,
 * Codex, Copilot). Written into each project directory at creation time to give AI
 * agents full project context. Two CLAUDE.md pointer files (root + .claude/) defer
 * to AGENTS.md via Claude Code's `@AGENTS.md` import syntax.
 *
 * The individual section builders (endpoints, storefront, block libraries,
 * PDP routing, example prompts, ...) live in `agentsMdSections.ts`; this module
 * composes them and owns the write path.
 */

import {
    buildAdobeIo,
    buildAppBuilderIntegrations,
    buildBlockLibraries,
    buildComponentRepositories,
    buildConsoleApiAccess,
    buildDocumentationRouting,
    buildEndpoints,
    buildHeader,
    buildHowToChangeThings,
    buildNotesForAgents,
    buildPdpRouting,
    buildReportingStyle,
    buildStorefront,
    buildTryAskingClaude,
} from './agentsMdSections';
import type { GeneratedFileWriter } from './generatedFileWriter';
import type { Project } from '@/types/base';
import type { Stack } from '@/types/stacks';

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Generated-file banner. Since ADR-013 (hash-and-skip) a hand edit is KEPT, not
 * overwritten: the refresh skips an edited file, reports it, and the AI
 * Capabilities modal shows "Edited — kept your version" — but the file then
 * stops receiving bundle updates until it is deleted and regenerated. The
 * banner states that trade honestly. (settings.json, which users customize
 * most, is MERGED instead — see claudeSettingsWriter.)
 */
const GENERATED_NOTICE =
    '<!-- GENERATED by Adobe Demo Builder. Edits are kept (never overwritten) but freeze this ' +
    'file at your version — it stops receiving bundle updates. Delete it and run ' +
    '"Regenerate AI Files" to return to the generated version. -->';

/**
 * Generate AGENTS.md content for a project.
 *
 * @param project - The project manifest
 * @param stacksConfig - Available stacks (used for display name lookup)
 * @returns AGENTS.md content as a string
 */
export function generateAgentsMd(project: Project, stacksConfig: Stack[]): string {
    const sections: string[] = [];

    sections.push(GENERATED_NOTICE);

    sections.push(buildHeader(project, stacksConfig));
    sections.push(buildHowToChangeThings());
    sections.push(buildEndpoints(project));
    sections.push(buildStorefront(project));
    sections.push(buildPdpRouting(project));
    sections.push(buildComponentRepositories(project));
    sections.push(buildBlockLibraries(project));
    sections.push(buildAdobeIo(project));
    sections.push(buildAppBuilderIntegrations(project));
    sections.push(buildConsoleApiAccess(project));
    sections.push(buildTryAskingClaude(project));
    sections.push(buildDocumentationRouting());
    sections.push(buildReportingStyle());
    sections.push(buildNotesForAgents(project));

    return sections.filter(Boolean).join('\n\n');
}

/**
 * One-line content of the CLAUDE.md pointer files. Claude Code resolves
 * `@AGENTS.md` against the file's parent directory and inlines the target's
 * content into context.
 */
const CLAUDE_MD_POINTER = 'see @AGENTS.md\n';

/**
 * Write AGENTS.md to the project root, plus CLAUDE.md pointer files at the
 * project root and in `.claude/`. The pointers defer to AGENTS.md so AI tools
 * that look for CLAUDE.md find the same content via a single import.
 *
 * All three files land through the ADR-013 GeneratedFileWriter seam
 * (hash-and-skip): a user-edited file is left in place and reported on
 * `writer.report()` rather than overwritten. No bundle write outside this
 * seam — a direct `fsPromises.writeFile` here would revert that file to
 * blind-overwrite behavior.
 *
 * @param projectPath - Path to the project root directory
 * @param project - The project manifest
 * @param stacksConfig - Available stacks (used for display name lookup)
 * @param writer - The ADR-013 hash-and-skip write seam for this refresh run
 */
export async function writeAgentsMd(
    projectPath: string,
    project: Project,
    stacksConfig: Stack[],
    writer: GeneratedFileWriter,
): Promise<void> {
    const content = generateAgentsMd(project, stacksConfig);

    await writer.write('AGENTS.md', content);
    await writer.write('CLAUDE.md', CLAUDE_MD_POINTER);
    await writer.write('.claude/CLAUDE.md', CLAUDE_MD_POINTER);
}
