#!/usr/bin/env node
/**
 * Point the FOCUSED mutation run at one module.
 *
 *   node scripts/focusModule.mjs src/features/eds/services/siteTools.ts
 *   node scripts/focusModule.mjs --check      # the two configs still agree with each other
 *
 * WHY. The focused run is described by two hand-maintained files that must agree:
 * `mutate` in stryker.focus.config.json and `testMatch` in jest.focus.config.js. The
 * note in the second one said, in as many words, that moving to the next module means
 * editing both together — which is a rule you follow until the night you do not. On
 * 2026-09-02 a new suite went into the focused config and not the sample one, and only
 * an enforcer caught it.
 *
 * When they disagree the failure does not look like a failure: a run where they DID
 * disagree reported 0% for seven modules and finished in 19 seconds, which reads as a
 * devastating result and was a run that never executed the tests. So this refuses to
 * write anything when it finds no suites, rather than producing a config that would
 * report a confident zero.
 *
 * Suites are found by this repo's mirror convention: a module under src is tested by the
 * same path under tests, plus any suite split from it with a hyphenated suffix.
 */
import { fileURLToPath } from 'url';
import { readFileSync, writeFileSync, existsSync, readdirSync, rmSync, realpathSync } from 'fs';
import { dirname, basename, join } from 'path';

const STRYKER = 'stryker.focus.config.json';
const JEST = 'jest.focus.config.js';
const SAMPLE_STRYKER = 'stryker.pl22.config.json';
const SAMPLE_JEST = 'jest.pl22.config.js';
const INCREMENTAL = 'reports/mutation/focus-incremental.json';

/** Every suite that mirrors `modulePath`, sorted, as repo-relative paths. */
export function suitesFor(modulePath) {
    if (!modulePath.startsWith('src/')) {
        throw new Error(`Expected a path under src/, got: ${modulePath}`);
    }
    const stem = basename(modulePath).replace(/\.tsx?$/, '');
    const dir = join('tests', dirname(modulePath).slice('src/'.length));
    if (!existsSync(dir)) return [];
    // A split suite is `<stem>-<topic>` or `<stem>.<topic>` — BOTH separators are in use
    // (`stateManager.disposal.test.ts` against `stateManager-projects.test.ts`), and
    // matching only the hyphen silently left one suite out of a run on 2026-09-02, which
    // understates the score for a module rather than failing.
    //
    // The separator is required: without it `stateManagerFake.test.ts` would be swept in
    // as though it tested the same subject.
    const isSplitSuite = (f) =>
        (f.startsWith(`${stem}-`) || f.startsWith(`${stem}.`)) && /\.test\.tsx?$/.test(f);
    return readdirSync(dir)
        .filter((f) => f === `${stem}.test.ts` || f === `${stem}.test.tsx` || isSplitSuite(f))
        .map((f) => join(dir, f))
        .sort();
}

function renderJest(modulePath, suites) {
    const header = readFileSync(JEST, 'utf8').split('const base = require')[0];
    const lines = suites.map((s) => `        '**/${s}',`).join('\n');
    return `${header}const base = require('./jest.config.js');

const node = base.projects.find((p) => p.displayName === 'node');

module.exports = {
    ...node,
    displayName: 'stryker-focus',
    // LISTED, not globbed: \`mutation-config-pairing\` verifies each named path
    // exists, and a glob is not a path it can check.
    // GENERATED by scripts/focusModule.mjs — re-run it rather than editing by hand.
    testMatch: [
${lines}
    ],
};
`;
}

/**
 * Add any MISSING suite to the SAMPLE config's list. Never removes.
 *
 * The sample covers twelve modules and its suite list is hand-maintained, so adding a
 * test file for any of them silently leaves it out. That happened TWICE on 2026-09-02,
 * both times caught by an enforcer rather than by anyone noticing.
 *
 * ADD-ONLY is not timidity, it is correctness. The mirror convention finds most suites
 * and not all of them — the webview tree, for one, does not mirror `src/` path for path.
 * A rewrite that dropped what it could not derive would remove EIGHT working entries
 * (measured, the first time this ran) and hand each of those modules a run with no tests,
 * which reports 0% and reads like a catastrophe. Entries it cannot account for are
 * REPORTED, so a genuinely stale one is still visible to a human.
 */
function syncSample() {
    const stryker = JSON.parse(readFileSync(SAMPLE_STRYKER, 'utf8'));
    const derived = [...new Set(stryker.mutate.flatMap((m) => suitesFor(m)))].sort();

    const src = readFileSync(SAMPLE_JEST, 'utf8');
    const listed = [...src.matchAll(/'\*\*\/([^']+)'/g)].map((m) => m[1]);
    const missing = derived.filter((s2) => !listed.includes(s2));
    const unexplained = listed.filter((s2) => !derived.includes(s2));

    if (missing.length) {
        const insertion = missing.map((s2) => `        '**/${s2}',`).join('\n');
        const anchor = `        '**/${listed[0]}',`;
        if (!src.includes(anchor)) {
            console.error(`Could not find an anchor entry in ${SAMPLE_JEST} to insert beside.`);
            process.exit(1);
        }
        writeFileSync(SAMPLE_JEST, src.replace(anchor, `${insertion}\n${anchor}`));
    }

    console.log(`${SAMPLE_JEST}: ${listed.length} listed, ${derived.length} derived from ${stryker.mutate.length} module(s).`);
    for (const a of missing) console.log(`  + ${a}`);
    for (const u of unexplained) console.log(`  ? ${u}   (listed but not derivable — left alone)`);
    if (!missing.length) console.log('  nothing missing.');
}

function main() {
    const arg = process.argv[2];

    if (arg === '--sync-sample') {
        syncSample();
        return;
    }
    const stryker = JSON.parse(readFileSync(STRYKER, 'utf8'));

    if (arg === '--check') {
        const [current] = stryker.mutate;
        const expected = suitesFor(current);
        const actual = [...readFileSync(JEST, 'utf8').matchAll(/'\*\*\/([^']+)'/g)].map((m) => m[1]);
        const missing = expected.filter((s) => !actual.includes(s));
        const extra = actual.filter((s) => !expected.includes(s));
        if (missing.length || extra.length) {
            console.error(`The focused configs disagree for ${current}:`);
            for (const s of missing) console.error(`  missing from ${JEST}: ${s}`);
            for (const s of extra) console.error(`  named in ${JEST} but not a suite for it: ${s}`);
            console.error(`\nRegenerate: node scripts/focusModule.mjs ${current}`);
            process.exit(1);
        }
        console.log(`Focused configs agree: ${current} <- ${expected.length} suite(s).`);
        return;
    }

    if (!arg) {
        console.error(
            'Usage: node scripts/focusModule.mjs <src/path/to/module.ts> | --check | --sync-sample'
        );
        process.exit(1);
    }
    if (!existsSync(arg)) {
        console.error(`No such module: ${arg}`);
        process.exit(1);
    }

    const suites = suitesFor(arg);
    if (suites.length === 0) {
        // Refusing is the whole point: a focused run with no suites reports 0% in
        // seconds and reads exactly like a catastrophic result.
        console.error(`No test suites mirror ${arg}. Refusing to write a config that would report a confident zero.`);
        process.exit(1);
    }

    const previous = stryker.mutate[0];
    stryker.mutate = [arg];
    writeFileSync(STRYKER, JSON.stringify(stryker, null, 4) + '\n');
    writeFileSync(JEST, renderJest(arg, suites));

    // The incremental cache belongs to the module it was built for.
    if (previous !== arg && existsSync(INCREMENTAL)) rmSync(INCREMENTAL);

    console.log(`Focused on ${arg}`);
    for (const s of suites) console.log(`  ${s}`);
    if (previous !== arg) console.log(`\nWas: ${previous}. Incremental cache cleared — the next run is cold.`);
}

/**
 * Only run the CLI when this file IS the command, not when another script imports it.
 * Without this, importing `suitesFor` executes main() against the IMPORTER's argv — the sweep
 * runner's `--minutes 480` was read as a module path and exited 1 before doing anything.
 */
const isEntryPoint =
    !!process.argv[1] &&
    existsSync(process.argv[1]) &&
    realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url));
if (isEntryPoint) main();
