#!/usr/bin/env node
/**
 * Point the FOCUSED mutation run at one module.
 *
 *   node scripts/focusModule.mjs src/features/eds/services/siteTools.ts
 *   node scripts/focusModule.mjs --check      # the two configs still agree with each other
 *
 * WHY. The focused run is described by two hand-maintained files that must agree:
 * `mutate` in stryker.focus.config.json and `testMatch` in jest.focus.config.js. The
 * note in the second one said, in as many words, that moving to the next module means
 * editing both together — which is a rule you follow until the night you do not. On
 * 2026-09-02 a new suite went into the focused config and not the sample one, and only
 * an enforcer caught it.
 *
 * When they disagree the failure does not look like a failure: a run where they DID
 * disagree reported 0% for seven modules and finished in 19 seconds, which reads as a
 * devastating result and was a run that never executed the tests. So this refuses to
 * write anything when it finds no suites, rather than producing a config that would
 * report a confident zero.
 *
 * Suites are found by this repo's mirror convention: a module under src is tested by the
 * same path under tests, plus any suite split from it with a hyphenated suffix.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync, rmSync } from 'fs';
import { dirname, basename, join } from 'path';

const STRYKER = 'stryker.focus.config.json';
const JEST = 'jest.focus.config.js';
const INCREMENTAL = 'reports/mutation/focus-incremental.json';

/** Every suite that mirrors `modulePath`, sorted, as repo-relative paths. */
export function suitesFor(modulePath) {
    if (!modulePath.startsWith('src/')) {
        throw new Error(`Expected a path under src/, got: ${modulePath}`);
    }
    const stem = basename(modulePath).replace(/\.tsx?$/, '');
    const dir = join('tests', dirname(modulePath).slice('src/'.length));
    if (!existsSync(dir)) return [];
    return readdirSync(dir)
        .filter((f) => f === `${stem}.test.ts` || f === `${stem}.test.tsx` ||
                       f.startsWith(`${stem}-`) && /\.test\.tsx?$/.test(f))
        .map((f) => join(dir, f))
        .sort();
}

function renderJest(modulePath, suites) {
    const header = readFileSync(JEST, 'utf8').split('const base = require')[0];
    const lines = suites.map((s) => `        '**/${s}',`).join('\n');
    return `${header}const base = require('./jest.config.js');

const node = base.projects.find((p) => p.displayName === 'node');

module.exports = {
    ...node,
    displayName: 'stryker-focus',
    // LISTED, not globbed: \`mutation-config-pairing\` verifies each named path
    // exists, and a glob is not a path it can check.
    // GENERATED by scripts/focusModule.mjs — re-run it rather than editing by hand.
    testMatch: [
${lines}
    ],
};
`;
}

function main() {
    const arg = process.argv[2];
    const stryker = JSON.parse(readFileSync(STRYKER, 'utf8'));

    if (arg === '--check') {
        const [current] = stryker.mutate;
        const expected = suitesFor(current);
        const actual = [...readFileSync(JEST, 'utf8').matchAll(/'\*\*\/([^']+)'/g)].map((m) => m[1]);
        const missing = expected.filter((s) => !actual.includes(s));
        const extra = actual.filter((s) => !expected.includes(s));
        if (missing.length || extra.length) {
            console.error(`The focused configs disagree for ${current}:`);
            for (const s of missing) console.error(`  missing from ${JEST}: ${s}`);
            for (const s of extra) console.error(`  named in ${JEST} but not a suite for it: ${s}`);
            console.error(`\nRegenerate: node scripts/focusModule.mjs ${current}`);
            process.exit(1);
        }
        console.log(`Focused configs agree: ${current} <- ${expected.length} suite(s).`);
        return;
    }

    if (!arg) {
        console.error(`Usage: node scripts/focusModule.mjs <src/path/to/module.ts> | --check`);
        process.exit(1);
    }
    if (!existsSync(arg)) {
        console.error(`No such module: ${arg}`);
        process.exit(1);
    }

    const suites = suitesFor(arg);
    if (suites.length === 0) {
        // Refusing is the whole point: a focused run with no suites reports 0% in
        // seconds and reads exactly like a catastrophic result.
        console.error(`No test suites mirror ${arg}. Refusing to write a config that would report a confident zero.`);
        process.exit(1);
    }

    const previous = stryker.mutate[0];
    stryker.mutate = [arg];
    writeFileSync(STRYKER, JSON.stringify(stryker, null, 4) + '\n');
    writeFileSync(JEST, renderJest(arg, suites));

    // The incremental cache belongs to the module it was built for.
    if (previous !== arg && existsSync(INCREMENTAL)) rmSync(INCREMENTAL);

    console.log(`Focused on ${arg}`);
    for (const s of suites) console.log(`  ${s}`);
    if (previous !== arg) console.log(`\nWas: ${previous}. Incremental cache cleared — the next run is cold.`);
}

main();
